### ISSUE TITLE
Server should be a generator

### ISSUE THREAD

**Issue by bergie** [noflo/noflo-xpress#71]
Currently NoFlo thinks the network has finished after setup, even though the HTTP server is actually listening for requests.

Either the server or the router(s) should be [generator](https://noflojs.org/documentation/components/#generator-components) that keeps the network alive until server stops.

**Comment by bergie** [comment]
Also, we need a way to _stop_ the server. Now when working with Flowhub and noflo-xpress, you can start a server, but Flowhub thinks the network finished immediately. And then restarting gives an error since the previous network is still running:

![screenshot 2017-04-05 at 18 28 20](https://cloud.githubusercontent.com/assets/3346/24716018/a9ffac24-1a2d-11e7-9bf7-46c56f441094.png)

**Comment by trustmaster** [comment]
I think this can be solved by adding a `stop` inport and adding proper lifecycle code to `Server` component. This also includes handling `SIGTERM` and `SIGKILL` via `process.on()`. Isn't a very big problem, but breaks backwards compatibility, so will be a version upgrade.

**Comment by bergie** [comment]
@trustmaster if we want `SIGTERM` and `SIGKILL` handling, maybe those should be done on NoFlo (or noflo-nodejs) side?

**Comment by bergie** [comment]
Note that a _stop_ inport is not strictly necessary for having proper lifecycle, though it is nice. The more important part is making the server a generator so that stopping the network will shut down the Express server.

**Comment by trustmaster** [comment]
@bergie ideally it should be handled by noflo-nodejs. Then `setUp()` and `tearDown()` methods can be used to manage generator state properly.

**Comment by bergie** [comment]
Fixed via #73
